Traceback (most recent call last):
  File "/home/weee/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import ngsolve and webgui
from ngsolve import *
from ngsolve.webgui import Draw

# draw the unit_square shape
Draw(unit_square.shape);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_28180/3621632522.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# import ngsolve and webgui[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mfrom[0m [0mngsolve[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mfrom[0m [0mngsolve[0m[0;34m.[0m[0mwebgui[0m [0;32mimport[0m [0mDraw[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;31m# draw the unit_square shape[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/bin/ngsolve/lib/python3/dist-packages/ngsolve/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     17[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mconfig[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m
[0;32m---> 19[0;31m [0;32mimport[0m [0mnetgen[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0;34m[0m[0m
[1;32m     21[0m [0;32mif[0m [0mconfig[0m[0;34m.[0m[0mis_python_package[0m [0;32mand[0m [0msys[0m[0;34m.[0m[0mplatform[0m[0;34m.[0m[0mstartswith[0m[0;34m([0m[0;34m'win'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/bin/ngsolve/lib/python3/dist-packages/netgen/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;32mdel[0m [0mos[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;34m[0m[0m
[0;32m---> 18[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mlibngpy[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0;34m[0m[0m
[1;32m     20[0m [0;32mfrom[0m [0mnetgen[0m[0;34m.[0m[0mlibngpy[0m[0;34m.[0m[0m_meshing[0m [0;32mimport[0m [0m_Redraw[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

